name: Weibo Sign-in

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python Script
        env:
          WEIBO_PARAMS: ${{ secrets.WEIBO_PARAMS }}
        run: python3 ./index.py

      - name: Get last commit message
        id: commit_message
        run: echo "last_commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

      - name: Push changes
        if: ${{!startsWith(steps.commit_message.outputs.last_commit_message, 'Updated at ') }}
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.USERNAME }}"
          git add .
          git commit -m "Updated at $(date -u +'%Y-%m-%d %H:%M:%S') UTC"
          git push
          
      - name: Force push changes
        if: ${{startsWith(steps.commit_message.outputs.last_commit_message, 'Updated at ') }}
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.USERNAME }}"
          git add .
          git reset --soft HEAD^
          git commit -m "Updated at $(date -u +'%Y-%m-%d %H:%M:%S') UTC"
          git push --force
