name: Aliyun Checkin

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python Script
        env:
          WEIBO_PARAMS: ${{ secrets.WEIBO_PARAMS }}

        run: python3 ./index.py
      
      - name: Get current UTC time
        run: echo "timestamp=$(date -u +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
        id: time

      - name: Push if there are any changes
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.USERNAME }}"
          git add .
          git commit -m "Log Upload at - ${{ steps.time.outputs.timestamp }} UTC" && git push || echo "No changes to commit"
          
